app_user_add:
    path: /user
    controller: App\Controller\UserController::addUser
    methods: [POST]

app_user_edit:
    path: /user
    controller: App\Controller\UserController::editUser
    methods: [PUT]

app_user_remove:
    path: /user
    controller: App\Controller\UserController::removeUser
    methods: [DELETE]
