app_user_add:
    path: /user
    controller: App\Controller\UserController::addUser
    methods: [POST]

app_user_edit:
    path: /user
    controller: App\Controller\UserController::editUser
    methods: [PUT]

app_user_remove:
    path: /user
    controller: App\Controller\UserController::removeUser
    methods: [DELETE]

app_user_get_all:
    path: /user
    controller: App\Controller\UserController::getAllUser
    methods: [GET]

app_user_get:
    path: /user/{id}
    controller: App\Controller\UserController::getUserById
    methods: [GET]

app_work_entry_add:
    path: /work-entry
    controller: App\Controller\WorkEntryController::addWorkEntry
    methods: [POST]